# Generated by Django 3.2.2 on 2021-05-13 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('picha', '0002_auto_20210513_2031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='Location',
            new_name='location',
        ),
    ]
